rm *.txt *.cor
sh mine.sh perso1
sh mine.sh perso2
sh mine.sh perso3
sh mine.sh perso4
sh mine.sh perso5
sh mine.sh perso6
sh mine.sh 42
sh mine.sh Backward
sh mine.sh Car
sh mine.sh Death
sh mine.sh Gagnant
sh mine.sh Octobre_Rouge_V4.2
sh mine.sh Survivor
sh mine.sh Torpille
sh mine.sh barriere
sh mine.sh ex
sh mine.sh jumper
sh mine.sh lde
sh mine.sh leeloo
sh mine.sh mat
sh mine.sh maxidef
sh mine.sh mortel
sh mine.sh new
sh mine.sh sebc
sh mine.sh slider2
sh mine.sh tdc2
sh mine.sh tdc3
sh mine.sh tdc4
sh mine.sh toto
sh mine.sh bee_gees
sh mine.sh bigzork
sh mine.sh fluttershy
sh mine.sh helltrain
sh mine.sh turtle
sh mine.sh zork
sh mine.sh sam_2.0
sh mine.sh doge
sh mine.sh Rainbow_dash
sh mine.sh youforkmytralala
sh mine.sh big_feet
sh mine.sh loose
sh mine.sh mandragore
sh mine.sh gedeon
sh mine.sh terminator
sh mine.sg ultimate-surrender
sh mine.sh _
sh mine.sh salamahenagalabadoun
sh mine.sh Machine-gun
sh mine.sh corelol
sh mine.sh MarineKing
sh mine.sh Kappa
sh mine.sh Wall
sh mine.sh Misaka_Mikoto
sh mine.sh Varimathras
sh mine justin_bee
sh mine.sh _honeybadger
sh mine.sh skynet
sh mine.sh live
sh mine.sh meowluigi
sh mine.sh dubo
sh mine.sh jinx
sh mine.sh THUNDER
sh mine.sh Asombra
sh mine.sh littlepuppy
sh mine.sh champ
sh mine.sh darksasuke
sh mine.sh casimir
sh mine.sh invalid1
sh mine.sh invalid2
sh mine.sh invalid3
sh mine.sh invalid4
sh mine.sh invalid5
sh mine.sh invalid6
sh mine.sh invalid7
sh mine.sh invalid8
sh mine.sh invalid9
sh mine.sh invalid10
sh mine.sh invalid11
sh mine.sh invalid12
sh mine.sh invalid13
sh mine.sh invalid14
sh mine.sh invalid15
sh mine.sh invalid16
sh mine.sh invalid17
sh mine.sh invalid18
sh mine.sh invalid19
sh mine.sh invalid20
sh mine.sh invalid21
sh mine.sh invalid22
sh mine.sh invalid23
sh mine.sh invalid24
sh mine.sh invalid25
sh mine.sh invalid26
sh mine.sh invalid27
sh mine.sh invalid28
sh mine.sh invalid29
sh mine.sh invalid30
sh mine.sh invalid31
sh mine.sh invalid32
sh mine.sh invalid33
sh mine.sh invalid34
sh mine.sh invalid35
sh mine.sh invalid36
sh mine.sh invalid37
sh mine.sh invalid38
sh mine.sh invalid39
sh mine.sh invalid40
sh mine.sh invalid41
sh mine.sh invalid42
sh mine.sh invalid43
sh mine.sh invalid44
sh mine.sh invalid45
sh mine.sh invalid46
sh mine.sh invalid47
sh mine.sh invalid48
sh mine.sh invalid49
sh mine.sh invalid50
sh mine.sh invalid51
sh mine.sh invalid52
sh mine.sh invalid53
sh mine.sh invalid54
sh mine.sh invalid55
sh mine.sh invalid56
sh mine.sh invalid57
sh mine.sh invalid58
sh mine.sh invalid59
sh mine.sh invalid60
sh mine.sh invalid61
sh mine.sh invalid62
sh mine.sh invalid63
sh mine.sh invalid64
sh mine.sh invalid65
sh mine.sh invalid66
sh mine.sh invalid67
sh mine.sh invalid68
sh mine.sh invalid69
sh mine.sh invalid70
sh mine.sh invalid71
sh mine.sh invalid72
sh mine.sh invalid73
sh mine.sh invalid74
sh mine.sh invalid75
sh mine.sh invalid76
sh mine.sh invalid77
sh mine.sh invalid78
sh mine.sh invalid79
sh mine.sh invalid80
sh mine.sh invalid81
sh mine.sh invalid82
sh mine.sh invalid83
sh mine.sh invalid84
sh mine.sh invalid85
sh mine.sh invalid86
sh mine.sh invalid87
sh mine.sh invalid88
sh mine.sh invalid89
sh mine.sh invalid90
sh mine.sh invalid91
sh mine.sh invalid92
sh mine.sh invalid93
sh mine.sh invalid94
sh mine.sh invalid95
sh mine.sh invalid96
sh mine.sh invalid97
sh mine.sh invalid98
sh mine.sh invalid99
sh mine.sh invalid100
sh mine.sh invalid101
sh mine.sh invalid102
sh mine.sh invalid104
